// Code generated by geta sync; DO NOT EDIT.

package routes

import (
	"github.com/koji-1009/geta"

	r_admin "github.com/koji-1009/geta/examples/register/routes/admin"
	r_admin_ping "github.com/koji-1009/geta/examples/register/routes/admin/ping"
	r_admin_users_id__role "github.com/koji-1009/geta/examples/register/routes/admin/users/id_/role"
	r_health "github.com/koji-1009/geta/examples/register/routes/health"
	r_stats_users "github.com/koji-1009/geta/examples/register/routes/stats/users"
	r_teams "github.com/koji-1009/geta/examples/register/routes/teams"
	r_teams_team_ "github.com/koji-1009/geta/examples/register/routes/teams/team_"
	r_teams_team__members "github.com/koji-1009/geta/examples/register/routes/teams/team_/members"
	r_teams_team__members_user_ "github.com/koji-1009/geta/examples/register/routes/teams/team_/members/user_"
	r_users "github.com/koji-1009/geta/examples/register/routes/users"
	r_users_by_role_role_ "github.com/koji-1009/geta/examples/register/routes/users/by-role/role_"
	r_users_events "github.com/koji-1009/geta/examples/register/routes/users/events"
	r_users_id_ "github.com/koji-1009/geta/examples/register/routes/users/id_"
	r_users_id__attachments "github.com/koji-1009/geta/examples/register/routes/users/id_/attachments"
	r_users_id__avatar "github.com/koji-1009/geta/examples/register/routes/users/id_/avatar"
	r_users_id__tags_index_ "github.com/koji-1009/geta/examples/register/routes/users/id_/tags/index_"
	r_users_import "github.com/koji-1009/geta/examples/register/routes/users/import"
	r_whoami "github.com/koji-1009/geta/examples/register/routes/whoami"
)

// Table is the route table of this tree.
func Table(env Env) geta.Table {
	return geta.Table{
		Root: Scope(env),
		Routes: []geta.Entry{
			{Path: "/admin/ping", Route: r_admin_ping.Route(env), Scopes: []geta.Scope{r_admin.Scope(env)}},
			{Path: "/admin/users/{id}/role", Route: r_admin_users_id__role.Route(env), Scopes: []geta.Scope{r_admin.Scope(env)}},
			{Path: "/health", Route: r_health.Route(env)},
			{Path: "/stats/users", Route: r_stats_users.Route(env)},
			{Path: "/teams", Route: r_teams.Route(env)},
			{Path: "/teams/{team}", Route: r_teams_team_.Route(env)},
			{Path: "/teams/{team}/members/{user}", Route: r_teams_team__members_user_.Route(env), Scopes: []geta.Scope{r_teams_team__members.Scope(env)}},
			{Path: "/users", Route: r_users.Route(env)},
			{Path: "/users/by-role/{role}", Route: r_users_by_role_role_.Route(env)},
			{Path: "/users/events", Route: r_users_events.Route(env)},
			{Path: "/users/import", Route: r_users_import.Route(env)},
			{Path: "/users/{id}", Route: r_users_id_.Route(env)},
			{Path: "/users/{id}/attachments", Route: r_users_id__attachments.Route(env)},
			{Path: "/users/{id}/avatar", Route: r_users_id__avatar.Route(env)},
			{Path: "/users/{id}/tags/{index}", Route: r_users_id__tags_index_.Route(env)},
			{Path: "/whoami", Route: r_whoami.Route(env)},
		},
	}
}
