// Code generated by geta sync; DO NOT EDIT.

package routes

import (
	"github.com/koji-1009/geta"

	r_bookmarks "github.com/koji-1009/geta/examples/bookmarks/routes/bookmarks"
	r_bookmarks_bookmark_ "github.com/koji-1009/geta/examples/bookmarks/routes/bookmarks/bookmark_"
	r_login "github.com/koji-1009/geta/examples/bookmarks/routes/login"
	r_logout "github.com/koji-1009/geta/examples/bookmarks/routes/logout"
	r_me "github.com/koji-1009/geta/examples/bookmarks/routes/me"
	r_metrics "github.com/koji-1009/geta/examples/bookmarks/routes/metrics"
)

// Table is the route table of this tree.
func Table(env Env) geta.Table {
	return geta.Table{
		Root: Scope(env),
		Routes: []geta.Entry{
			{Path: "/bookmarks", Route: r_bookmarks.Route(env)},
			{Path: "/bookmarks/{bookmark}", Route: r_bookmarks_bookmark_.Route(env)},
			{Path: "/login", Route: r_login.Route(env)},
			{Path: "/logout", Route: r_logout.Route(env)},
			{Path: "/me", Route: r_me.Route(env)},
			{Path: "/metrics", Route: r_metrics.Route(env)},
		},
	}
}
