// Code generated by geta sync; DO NOT EDIT.

package routes

import (
	"github.com/koji-1009/geta"

	r_admin "github.com/koji-1009/geta/examples/auth/routes/admin"
	r_admin_whoami "github.com/koji-1009/geta/examples/auth/routes/admin/whoami"
	r_login "github.com/koji-1009/geta/examples/auth/routes/login"
	r_logout "github.com/koji-1009/geta/examples/auth/routes/logout"
	r_me "github.com/koji-1009/geta/examples/auth/routes/me"
	r_me_events "github.com/koji-1009/geta/examples/auth/routes/me/events"
	r_public "github.com/koji-1009/geta/examples/auth/routes/public"
)

// Table is the route table of this tree.
func Table(env Env) geta.Table {
	return geta.Table{
		Root: Scope(env),
		Routes: []geta.Entry{
			{Path: "/admin/whoami", Route: r_admin_whoami.Route(env), Scopes: []geta.Scope{r_admin.Scope(env)}},
			{Path: "/login", Route: r_login.Route(env)},
			{Path: "/logout", Route: r_logout.Route(env)},
			{Path: "/me", Route: r_me.Route(env)},
			{Path: "/me/events", Route: r_me_events.Route(env)},
			{Path: "/public", Route: r_public.Route(env)},
		},
	}
}
