// Code generated by geta sync; DO NOT EDIT.

package routes

import (
	"testing"

	"github.com/koji-1009/geta/getatest"
)

// TestTableAssembles runs every geta.New check on Table, through getatest.New,
// which fails the test on an assembly error. testEnv is the application's:
// define func testEnv(testing.TB) Env in a _test.go file of this package,
// returning an Env the table can be assembled with.
// The options are Options(env), from options.go, as main assembles the app.
func TestTableAssembles(t *testing.T) {
	env := testEnv(t)
	getatest.New(t, Table(env), Options(env)...)
}
