// Code generated by geta sync; DO NOT EDIT.

package routes

import (
	"github.com/koji-1009/geta"

	r_bookings_booking_ "github.com/koji-1009/geta/examples/booking/routes/bookings/booking_"
	r_bookings_booking__changes "github.com/koji-1009/geta/examples/booking/routes/bookings/booking_/changes"
	r_bookings_booking__history "github.com/koji-1009/geta/examples/booking/routes/bookings/booking_/history"
	r_health "github.com/koji-1009/geta/examples/booking/routes/health"
	r_me "github.com/koji-1009/geta/examples/booking/routes/me"
	r_rooms "github.com/koji-1009/geta/examples/booking/routes/rooms"
	r_rooms_room_ "github.com/koji-1009/geta/examples/booking/routes/rooms/room_"
	r_rooms_room__bookings "github.com/koji-1009/geta/examples/booking/routes/rooms/room_/bookings"
	r_rooms_room__live "github.com/koji-1009/geta/examples/booking/routes/rooms/room_/live"
)

// Table is the route table of this tree.
func Table(env Env) geta.Table {
	return geta.Table{
		Root: Scope(env),
		Routes: []geta.Entry{
			{Path: "/bookings/{booking}", Route: r_bookings_booking_.Route(env)},
			{Path: "/bookings/{booking}/changes", Route: r_bookings_booking__changes.Route(env)},
			{Path: "/bookings/{booking}/history", Route: r_bookings_booking__history.Route(env)},
			{Path: "/health", Route: r_health.Route(env)},
			{Path: "/me", Route: r_me.Route(env)},
			{Path: "/rooms", Route: r_rooms.Route(env)},
			{Path: "/rooms/{room}", Route: r_rooms_room_.Route(env)},
			{Path: "/rooms/{room}/bookings", Route: r_rooms_room__bookings.Route(env)},
			{Path: "/rooms/{room}/live", Route: r_rooms_room__live.Route(env)},
		},
	}
}
